# Generated by Django 5.2.16 on 2026-07-25 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_transaction_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transanction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Payments.transaction')),
            ],
        ),
    ]
