# Generated by Django 5.2.16 on 2026-07-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_receipt'),
        ('Users', '0003_parentuserlogginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='Users.parentusers'),
        ),
    ]
