# Generated by Django 5.2.16 on 2026-07-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptsSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transanction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='Payments.transaction'),
        ),
    ]
