# Generated by Django 5.2.16 on 2026-07-26 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_receipt_pdf'),
        ('Users', '0003_parentuserlogginsession'),
        ('schools', '0002_school_fee_amount_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.school'),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_sent', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('trans_fee', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='schools.school')),
                ('transanction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Users.parentusers')),
            ],
        ),
    ]
