# Generated by Django 5.2.16 on 2026-07-25 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_parentusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUserLogginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.parentusers')),
            ],
        ),
    ]
