# Generated by Django 5.2.16 on 2026-07-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('email', models.EmailField(max_length=254)),
                ('official_document', models.FileField(upload_to='school_documents/')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('denied', 'Denied'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('phone_numbers', models.JSONField(blank=True, default=list, help_text="List of contact phone numbers, e.g. ['+265991234567'].")),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('bank', 'Bank'), ('mobile', 'Mobile')], max_length=10)),
                ('provider', models.CharField(help_text='e.g. Airtel Money, NBS, NBM, TNM Mpamba.', max_length=100)),
                ('account_no', models.CharField(help_text='Bank account number (bank) or phone number (mobile).', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='schools.school')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['school', '-is_active'],
                'constraints': [models.UniqueConstraint(fields=('school', 'payment_type', 'account_no'), name='unique_school_payment_channel')],
            },
        ),
    ]
