# Generated by Django 5.2.16 on 2026-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('university', 'University'), ('college', 'College')], default='secondary', max_length=20),
        ),
    ]
