# Generated by Django 5.2.16 on 2026-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_fee_amount_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(default='Lilongwe', max_length=300),
        ),
    ]
