# Generated by Django 5.2.16 on 2026-07-27 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accountants',
            field=models.ManyToManyField(blank=True, related_name='accountant_schools', to=settings.AUTH_USER_MODEL),
        ),
    ]
